=== hmcts/pip-data-management/src/main/resources/schemas/care_standards_list.json
{
  "$defs": {
    "address": {
      "title": "Address Details",
      "type": "object",
      "properties": {
        "line": {
          "title": "Address Line",
          "type": "array",
          "default": [],
          "items": {
            "title": "Items",
            "type": "string",
            "default": "",
            "examples": [
              "THE LAW COURTS"
            ],
            "pattern": "^(?!.*<[^>]+>).*$"
          }
        },
        "town": {
          "title": "Town",
          "description": "The town for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridge"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        },
        "county": {
          "title": "County",
          "description": "The county for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridgeshire"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        },
        "postCode": {
          "title": "Address Postcode",
          "type": "string",
          "default": "",
          "examples": [
            "PR1 2LL"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        }
      }
    },
    "venueContact": {
      "title": "Contact Details for a venue",
      "type": "object",
      "properties": {
        "venueTelephone": {
          "description": "Telephone number for the venue",
          "title": "Venue Telephone",
          "type": "string",
          "default": "",
          "examples": [
            "01772 844700"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        },
        "venueEmail": {
          "description": "Email for the venue",
          "title": "Venue Email",
          "type": "string",
          "default": "",
          "examples": [
            "court1@moj.gov.uk"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        }
      }
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "object",
  "required": [
    "document",
    "courtLists",
    "venue"
  ],
  "properties": {
    "document": {
      "title": "document",
      "type": "object",
      "required": [
        "publicationDate"
      ],
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date + time the list was published",
          "type": "string",
          "examples": [
            "2016-09-13T23:30:52.123Z"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        }
      }
    },
    "venue": {
      "title": "venue",
      "type": "object",
      "required": [
        "venueContact"
      ],
      "properties": {
        "venueContact": {
          "description": "Contact details for the venue",
          "title": "Venue Contact",
          "$ref": "#/$defs/venueContact",
          "required": ["venueTelephone", "venueEmail"]
        }
      }
    },
    "locationDetails": {
      "title": "Location Details",
      "type": "object",
      "properties": {
        "jurisdiction": {
          "description": "Jurisdiction",
          "title": "Jurisdiction",
          "type": "string",
          "default": "",
          "examples": [
            "Family court"
          ],
          "pattern": "^(?!.*<[^>]+>).*$"
        }
      }
    },
    "courtLists": {
      "title": "Court Lists",
      "type": "array",
      "items": {
        "title": "Court list",
        "type": "object",
        "required": [
          "courtHouse"
        ],
        "properties": {
          "courtHouse": {
            "title": "Court House",
            "description": "The court house that owns the court rooms",
            "type": "object",
            "required": [
              "courtRoom",
              "courtHouseName"
            ],
            "properties": {
              "courtHouseName": {
                "description": "Name of the court house",
                "title": "Court House Name",
                "type": "string",
                "default": "",
                "examples": [
                  "PRESTON"
                ],
                "pattern": "^(?!.*<[^>]+>).*$"
              },
              "courtHouseAddress": {
                "description": "The address for the court house",
                "title": "Court House Address",
                "$ref": "#/$defs/address"
              },
              "courtRoom": {
                "type": "array",
                "items": {
                  "title": "Court Room",
                  "description": "The court room that owns the court rooms",
                  "type": "object",
                  "required": [
                    "session"
                  ],
                  "properties": {
                    "session": {
                      "type": "array",
                      "items": {
                        "title": "Session",
                        "description": "Session associated with the court in the publication",
                        "type": "object",
                        "required": [
                          "sittings",
                          "sessionStartTime"
                        ],
                        "properties": {
                          "sessionStartTime": {
                            "description": "Session start time rfc3999",
                            "title": "Session start time",
                            "type": "string",
                            "examples": [
                              "2021-09-09t16:41:07.394"
                            ],
                            "default": "",
                            "pattern": "^(?!.*<[^>]+>).*$"
                          },
                          "sittings": {
                            "title": "Sittings",
                            "type": "array",
                            "default": [],
                            "items": {
                              "type": "object",
                              "required": [
                                "sittingStart",
                                "sittingEnd",
                                "hearing"
                              ],
                              "properties": {
                                "sittingStart": {
                                  "description": "Sitting Start Time",
                                  "title": "Sitting Start",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^(?!.*<[^>]+>).*$"
                                },
                                "sittingEnd": {
                                  "description": "Sitting End Time",
                                  "title": "Sitting End",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^(?!.*<[^>]+>).*$"
                                },
                                "hearing": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "required": [
                                      "case"
                                    ],
                                    "description": "Hearing details of the case and associated details for the sitting",
                                    "title": "Hearing",
                                    "properties": {
                                      "hearingType": {
                                        "description": "Type of hearing being presented",
                                        "title": "Hearing Type",
                                        "type": "string",
                                        "examples": [
                                          "mda"
                                        ],
                                        "default": "",
                                        "pattern": "^(?!.*<[^>]+>).*$"
                                      },
                                      "case": {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "title": "Case",
                                          "description": "Case Details",
                                          "required": [
                                            "caseName",
                                            "caseNumber"
                                          ],
                                          "properties": {
                                            "caseName": {
                                              "title": "Case Name",
                                              "description": "Case name is not always present but should be where available displayed",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "A Vs B"
                                              ],
                                              "pattern": "^(?!.*<[^>]+>).*$"
                                            },
                                            "caseNumber": {
                                              "title": "Case Number",
                                              "description": "A number identifying a case",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "45684548"
                                              ],
                                              "pattern": "^(?!.*<[^>]+>).*$"
                                            },
                                            "caseSequenceIndicator": {
                                              "title": "Case Sequence Indicator",
                                              "description": "The case sequence indicator",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "2 of 3"
                                              ],
                                              "pattern": "^(?!.*<[^>]+>).*$"
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== hmcts/pip-data-management/src/test/resources/mocks/primaryHealthListWithNewLines.json
{
  "document": {
    "publicationDate": "2022-10-04T09:00:52.123Z"
  },
  "venue": {
    "venueContact": {
      "venueTelephone": "01772\r\n 844700",
      "venueEmail": "court1@moj.\r\ngov.uk"
    }
  },
  "locationDetails": {
    "jurisdiction": "Tribunal\r\n"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "The\r\n Court House",
        "courtHouseAddress": {
          "line": [
            "Court \r\nStreet"
          ],
          "town": "Court \r\n Town",
          "county": "Court \r\n County",
          "postCode": "SK4\r\n 5LE"
        },
        "courtRoom": [
          {
            "session": [
              {
                "sessionStartTime": "2022-10-05T09:00:52.123Z",
                "sittings": [
                  {
                    "sittingStart": "2022-10-05T11:00:52.123Z",
                    "sittingEnd": "2022-10-06T11:30:52.123Z",
                    "hearing": [
                      {
                        "hearingType": "Remote -\r\n Teams",
                        "case": [
                          {
                            "caseName": "A Vs \r\nB",
                            "caseNumber": "4568\r\n4548",
                            "caseSequenceIndicator": "1\r\n of 2"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}

=== hmcts/pip-data-management/src/test/resources/mocks/careStandardsListWithNewLines.json
{
  "document": {
    "publicationDate": "2022-10-04T09:00:52.123Z"
  },
  "venue": {
    "venueContact": {
      "venueTelephone": "01772\r\n 844700",
      "venueEmail": "court1@moj.gov\r\n.uk"
    }
  },
  "locationDetails": {
    "jurisdiction": "Tribunal\r\n"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "The Court \r\nHouse",
        "courtHouseAddress": {
          "line": [
            "Court\r\n Street"
          ],
          "town": "Court \r\nTown",
          "county": "Court \r\n County",
          "postCode": "SK4\r\n 5LE"
        },
        "courtRoom": [
          {
            "session": [
              {
                "sessionStartTime": "2022-10-05T09:00:52.123Z",
                "sittings": [
                  {
                    "sittingStart": "2022-10-05T11:00:52.123Z",
                    "sittingEnd": "2022-10-06T11:30:52.123Z",
                    "hearing": [
                      {
                        "hearingType": "Remote - \r\nTeams",
                        "case": [
                          {
                            "caseName": "A Vs \r\nB",
                            "caseNumber": "4568\r\n4548",
                            "caseSequenceIndicator": "1 of\r\n 2"
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
