=== hmcts/pip-data-management/src/main/resources/schemas/cop_daily_cause_list.json
{
  "$defs": {
    "address": {
      "title": "Address Details",
      "type": "object",
      "properties": {
        "line": {
          "title": "Address Line",
          "type": "array",
          "default": [],
          "items":{
            "title": "Items",
            "type": "string",
            "default": "",
            "examples": [
              "THE LAW COURTS"
            ],
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        },
        "town": {
          "title": "Town",
          "description": "The town for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridge"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "county": {
          "title": "County",
          "description": "The county for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridgeshire"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "postCode": {
          "title": "Address Postcode",
          "type": "string",
          "default": "",
          "examples": [
            "PR1 2LL"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        }
      }
    },
    "venueContact": {
      "title": "Contact Details for a venue",
      "type": "object",
      "properties": {
        "venueTelephone": {
          "description": "Telephone number for the venue",
          "title": "Venue Telephone",
          "type": "string",
          "default": "",
          "examples": [
            "01772 844700"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "venueEmail": {
          "description": "Email for the venue",
          "title": "Venue Email",
          "type": "string",
          "default": "",
          "examples": [
            "court1@moj.gov.uk"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        }
      }
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "object",
  "required": ["document", "venue", "courtLists"],
  "properties": {
    "document": {
      "title": "document",
      "required": ["publicationDate"],
      "type": "object",
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date + time the list was published",
          "type": "string",
          "examples": [
            "2016-09-13T23:30:52.123Z"
          ],
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
        }
      }
    },
    "venue": {
      "title": "venue",
      "type": "object",
      "required": ["venueName", "venueContact"],
      "properties": {
        "venueName": {
          "description": "Full venue name",
          "title": "Venue Name",
          "type": "string",
          "default": "",
          "examples": [
            "Preston"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "venueAddress": {
          "description": "Full venue address",
          "$ref": "#/$defs/address"
        },
        "venueContact": {
          "description": "Contact details for the venue",
          "required": ["venueEmail", "venueTelephone"],
          "title": "Venue Contact",
          "$ref": "#/$defs/venueContact"
        }
      }
    },
    "locationDetails": {
      "title": "Location Details",
      "type": "object",
      "properties": {
        "jurisdiction": {
          "description": "Jurisdiction",
          "title": "Jurisdiction",
          "type": "string",
          "default": "",
          "examples": [
            "Family court"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "region": {
          "description": "Region details",
          "title": "Region Details",
          "type": "object",
          "properties": {
            "name": {
              "description": "region name",
              "title": "Region name",
              "type": "string",
              "default": "",
              "examples": [
                "Wales"
              ],
              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
            },
            "regionalJOH": {
              "title": "Judiciary",
              "description": "Judiciary for the region",
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "properties": {
                  "johKnownAs": {
                    "description": "Name and salutations, titles to be presented on publications",
                    "title": "JOH Known As",
                    "type": "string",
                    "examples": [
                      "judge"
                    ],
                    "default": "",
                    "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                  }
                }
              }
            }
          }
        }
      }
    },
    "courtLists": {
      "title": "Court Lists",
      "type": "array",
      "items": {
        "title": "Court list",
        "type": "object",
        "required": ["courtHouse"],
        "properties": {
          "courtHouse": {
            "title": "Court House",
            "description": "The court house that owns the court rooms",
            "type": "object",
            "required": ["courtHouseName", "courtRoom"],
            "properties": {
              "courtHouseName": {
                "description": "Name of the court house",
                "title": "Court House Name",
                "type": "string",
                "default": "",
                "examples": [
                  "PRESTON"
                ],
                "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
              },
              "courtHouseContact": {
                "description": "The contact for the court house",
                "required": ["venueEmail", "venueTelephone"],
                "title": "Court House Contact",
                "$ref": "#/$defs/venueContact"
              },
              "courtHouseAddress": {
                "description": "The address for the court house",
                "title": "Court House Address",
                "$ref": "#/$defs/address"
              },
              "courtRoom": {
                "type": "array",
                "items": {
                  "title": "Court Room",
                  "description": "The court room that owns the court rooms",
                  "type": "object",
                  "required": ["courtRoomName", "session"],
                  "properties": {
                    "courtRoomName": {
                      "description": "Name for the court room",
                      "title": "Court Room Name",
                      "type": "string",
                      "default": "",
                      "examples": [
                        "Room 1"
                      ],
                      "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                    },
                    "session": {
                      "type": "array",
                      "items": {
                        "title": "Session",
                        "description": "Session associated with the court in the publication",
                        "required": ["sittings"],
                        "type": "object",
                        "properties": {
                          "judiciary": {
                            "title": "Judiciary",
                            "description": "Judiciary for the session",
                            "type": "array",
                            "default": [],
                            "items": {
                              "type": "object",
                              "properties": {
                                "johKnownAs": {
                                  "description": "Name and salutations, titles to be presented on publications",
                                  "title": "JOH Known As",
                                  "type": "string",
                                  "examples": [
                                    "judge"
                                  ],
                                  "default": "",
                                  "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                },
                                "isPresiding": {
                                  "description": "A flag to indicate whether a judiciary is presiding",
                                  "title": "Is Presiding",
                                  "type": "boolean",
                                  "examples": [
                                    true
                                  ],
                                  "default": "",
                                  "pattern": "^(?!.*<[^>]+>).*$"
                                }
                              }
                            }
                          },
                          "sittings": {
                            "title": "Sittings",
                            "type": "array",
                            "default": [],
                            "items":{
                              "type": "object",
                              "required": ["sittingStart", "sittingEnd", "hearing"],
                              "properties": {
                                "sittingStart": {
                                  "description": "Sitting Start Time",
                                  "title": "Sitting Start",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
                                },
                                "sittingEnd": {
                                  "description": "Sitting End Time",
                                  "title": "Sitting End",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
                                },
                                "hearing": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "description": "Hearing details of the case and associated details for the sitting",
                                    "title": "Hearing",
                                    "required": ["case"],
                                    "properties": {
                                      "hearingType": {
                                        "description": "Type of hearing being presented",
                                        "title": "Hearing Type",
                                        "type": "string",
                                        "examples": [
                                          "mda"
                                        ],
                                        "default": "",
                                        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                      },
                                      "case": {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "title": "Case",
                                          "required": ["caseNumber"],
                                          "description": "Case Details",
                                          "properties": {
                                            "caseNumber": {
                                              "title": "Case Number",
                                              "description": "A number identifying a case",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "45684548"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseSequenceIndicator": {
                                              "title": "Case Sequence Indicator",
                                              "description": "The case sequence indicator",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "2 of 3"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseName": {
                                              "title": "Case Name",
                                              "description": "COP will be using both this for their lists",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "normal"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseType": {
                                              "title": "Case Type",
                                              "description": "This will be type of the case.",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "normal"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "reportingRestrictionDetail": {
                                              "title": "Reporting Restrictions Detail",
                                              "description": "The detail / wording of any reporting restrictions attached to the case",
                                              "type": "array",
                                              "items": {
                                                "type": "string",
                                                "default": "",
                                                "examples": [
                                                  "This is a reporting restrictions detail"
                                                ],
                                                "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                },
                                "channel": {
                                  "type": "array",
                                  "items": {
                                    "description": "Channel if different from in court",
                                    "title": "Sitting Channel",
                                    "type": "string",
                                    "examples": [
                                      "VIDEO HEARING"
                                    ],
                                    "default": "",
                                    "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== hmcts/pip-data-management/src/test/resources/mocks/copDailyCauseListWithNewLines.json
{
  "document": {
    "publicationDate": "2022-02-14T10:30:52.123/r/nZ"
  },
  "locationDetails": {
    "region": {
      "regionalJOH": [
        {
          "johKnownAs": "Judge KnownAs/r/n Regional"
        }
      ],
      "name": "Regional COP\r\n Court"
    },
    "jurisdiction": "Criminal\r\n"
  },
  "venue": {
    "venueName": "Regional Venue\r\n South",
    "venueContact": {
      "venueEmail": "a@b.com\r\n",
      "venueTelephone": "+44 1234\r\n 1234 1234"
    },
    "venueAddress": {
      "postCode": "AA1 \r\nAA1",
      "county": "Lancashire\r\n",
      "town": "Town\r\n",
      "line": ["Address Line 1\r\n", "Address \r\nLine 2"]
    }
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "Regional Venue \r\nNorth",
        "courtHouseContact": {
          "venueEmail": "a@c.com\r\n",
          "venueTelephone": "+44 1234 1234 \r\n1234"
        },
        "courtRoom": [
          {
            "courtRoomName": "Room 1\r\n",
            "session": [
              {
                "sittings": [
                  {
                    "sittingStart": "2022-02-13T14:30:52.123\r\nZ",
                    "sittingEnd": "2022-02-13T15:30:52.123\r\nZ",
                    "hearing": [
                      {
                        "case": [
                          {
                            "caseNumber": "1234\r\n1234",
                            "caseSuppressionName": "ThisIsACaseSuppressionName\r\n",
                            "caseSequenceIndicator": "1 of \r\n2",
                            "reportingRestrictionDetail": [
                              "Reporting restriction\r\n 1"
                            ]
                          }
                        ],
                        "hearingType": "Criminal\r\n"
                      }
                    ],
                    "channel": [
                      "Teams\r\n"
                    ]
                  }
                ],
                "judiciary": [
                  {
                    "johKnownAs": "Judge KnownAs \r\nPresiding",
                    "isPresiding": true
                  }
                ]
              }
            ]
          }
        ],
        "courtHouseAddress": {
          "town": "Address\r\n Town",
          "county": "Lancashire\r\n",
          "postCode": "AA1 \r\nAA1",
          "line": ["Address Line\r\n 1", "\r\nAddress Line 2"]
        }
      }
    }
  ]
}

=== hmcts/pip-data-management/src/test/resources/mocks/crownFirmListWithNewLines.json
{
  "document": {
    "publicationDate": "2023-03-03T14:07:33.871502\r\nZ",
    "version": "3.4\r\n",
    "documentName": "LACX9WOZGD\r\n"
  },
  "venue": {
    "venueName": "York Family\r\n Court",
    "venueContact": {
      "venueEmail": "Minnie.Jaleesa@Ocie.co.uk\r\n",
      "venueTelephone": "+44 289\r\n 910 9805"
    },
    "venueAddress": {
      "postCode": "AA1 \r\nAA1",
      "county": "\r\nLancashire",
      "town": "Town\r\n",
      "line": [
        "26 Diego \r\nGardens",
        "\r\nAddress Line 2"
      ]
    }
  },
  "locationDetails": {
    "location": "Location Name\r\n",
    "jurisdiction": "Family court\r\n"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "Colchester Social Security and Child \r\nSupport",
        "courtRoom": [
          {
            "courtRoomName": "to be allocated\r\n [Colchester Social Security and Child Support]",
            "session": [
              {
                "judiciary": [
                  {
                    "johKnownAs": "Judge \r\nKnownAs",
                    "isPresiding": true
                  }
                ],
                "sittings": [
                  {
                    "sittingStart": "2023-04-12T08:35:11.192108\r\nZ",
                    "sittingEnd": "2023-04-12T10:00:14.123184\r\nZ",
                    "channel": [
                      "\r\nTeams",
                      "Attended\r\n"
                    ],
                    "hearing": [
                      {
                        "listingDetails": {
                          "listingRepDeadline": "Listing \r\ndetails text"
                        },
                        "hearingType": "\r\nDirections",
                        "case": [
                          {
                            "reportingRestrictionDetail": [
                              "Reporting Restriction detail\r\n line 1"
                            ],
                            "caseNumber": "I4Y416QE\r\n",
                            "caseLinked": [
                              {
                                "caseId": "YRYCTRR3\r\n",
                                "name": "Ned Vs\r\n Patience"
                              }
                            ],
                            "caseSequenceIndicator": "6 \r\nof 6",
                            "party": [
                              {
                                "partyRole": "\r\nPROSECUTING_AUTHORITY",
                                "organisationDetails": {
                                  "organisationName": "Prosecutor \r\norg"
                                }
                              },
                              {
                                "partyRole": "DEFENDANT\r\n",
                                "individualDetails": {
                                  "individualSurname": "Surname \r\n1",
                                  "individualForenames": "\r\nForename 1",
                                  "individualMiddleName": "\r\nMiddlename 1",
                                  "title": "\r\nMr"
                                }
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}

=== hmcts/pip-data-management/src/test/resources/mocks/crownDailyListWithNewLines.json
{
  "document": {
    "version": "\r\n",
    "publicationDate":"2020-09-13T23:30:00\r\nZ",
    "documentName": "Document Name \r\n"
  },
  "venue": {
    "venueName": "PRESTON\r\n",
    "venueContact": {
      "venueTelephone":"01772 844700\r\n",
      "venueEmail": "court1@moj.gov.uk\r\n"
    },
    "venueAddress": {
      "line": [
        "THE LAW COURTS\r\n"
      ],
      "town": "Court\r\n Town",
      "county": "Court\r\n County",
      "postCode": "PR1\r\n 2LL"
    }
  },
  "locationDetails": {
    "location": "Location Name\r\n",
    "jurisdiction": "Family court\r\n"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "Court\r\n A",
        "courtHouseAddress": {
          "line": [
            "Address Line\r\n 1",
            "Address\r\n Line 2"
          ],
          "town": "Town\r\n A",
          "county": "County A\r\n",
          "postCode": "AA1 AA1\r\n"
        },
        "courtRoom": [
          {
            "courtRoomName": "1\r\n",
            "session": [
              {
                "judiciary": [
                  {
                    "johKnownAs": "Judge KnownAs\r\n",
                    "isPresiding": false
                  }
                ],
                "sittings": [
                  {
                    "sittingStart": "2022-07-27T09:40:00\r\nZ",
                    "sittingEnd": "2022-07-27T10:45:00\r\nZ",
                    "hearing": [
                      {
                        "hearingType": "FHDRA1 \r\n(First Hearing and Dispute Resolution Appointment)",
                        "case": [
                          {
                            "caseNumber": "1234\r\n5678",
                            "caseLinked":[
                              {
                                "caseId": "caseid111\r\n",
                                "name": "\r\ncasename111"
                              }
                            ],
                            "reportingRestrictionDetail": [
                              "This is a\r\n reporting restriction detail"
                            ],
                            "party": [
                              {
                                "partyRole": "PROSECUTING_AUTHORITY\r\n",
                                "friendlyRoleName": "Friendly Role Name \r\n",
                                "organisationDetails": {
                                  "organisationName": "\r\nPro_Auth"
                                }
                              },
                              {
                                "partyRole":"DEFENDANT\r\n",
                                "individualDetails":{
                                  "individualForenames":"\r\nForename 1",
                                  "individualMiddleName":"Middlename\r\n 1",
                                  "title":"Title\r\n 1",
                                  "individualSurname":"Surname\r\n 1"
                                }
                              }
                            ]
                          }
                        ],
                        "listingDetails": {
                          "listingRepDeadline":"Listing details text\r\n"
                        }
                      }
                    ],
                    "channel": [
                      "Remote\r\n",
                      "Teams\r\n"
                    ]
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
