=== hmcts/pip-data-management/src/main/resources/schemas/cop_daily_cause_list.json
{
  "$defs": {
    "address": {
      "title": "Address Details",
      "type": "object",
      "properties": {
        "line": {
          "title": "Address Line",
          "type": "array",
          "default": [],
          "items":{
            "title": "Items",
            "type": "string",
            "default": "",
            "examples": [
              "THE LAW COURTS"
            ],
            "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
          }
        },
        "town": {
          "title": "Town",
          "description": "The town for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridge"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "county": {
          "title": "County",
          "description": "The county for the address",
          "type": "string",
          "default": "",
          "examples": [
            "Cambridgeshire"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "postCode": {
          "title": "Address Postcode",
          "type": "string",
          "default": "",
          "examples": [
            "PR1 2LL"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        }
      }
    },
    "venueContact": {
      "title": "Contact Details for a venue",
      "type": "object",
      "properties": {
        "venueTelephone": {
          "description": "Telephone number for the venue",
          "title": "Venue Telephone",
          "type": "string",
          "default": "",
          "examples": [
            "01772 844700"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "venueEmail": {
          "description": "Email for the venue",
          "title": "Venue Email",
          "type": "string",
          "default": "",
          "examples": [
            "court1@moj.gov.uk"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        }
      }
    }
  },
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "object",
  "required": ["document", "venue", "courtLists"],
  "properties": {
    "document": {
      "title": "document",
      "required": ["publicationDate"],
      "type": "object",
      "properties": {
        "publicationDate": {
          "title": "Publication date",
          "description": "The date + time the list was published",
          "type": "string",
          "examples": [
            "2016-09-13T23:30:52.123Z"
          ],
          "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
        }
      }
    },
    "venue": {
      "title": "venue",
      "type": "object",
      "required": ["venueName", "venueContact"],
      "properties": {
        "venueName": {
          "description": "Full venue name",
          "title": "Venue Name",
          "type": "string",
          "default": "",
          "examples": [
            "Preston"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "venueAddress": {
          "description": "Full venue address",
          "$ref": "#/$defs/address"
        },
        "venueContact": {
          "description": "Contact details for the venue",
          "required": ["venueEmail", "venueTelephone"],
          "title": "Venue Contact",
          "$ref": "#/$defs/venueContact"
        }
      }
    },
    "locationDetails": {
      "title": "Location Details",
      "type": "object",
      "properties": {
        "jurisdiction": {
          "description": "Jurisdiction",
          "title": "Jurisdiction",
          "type": "string",
          "default": "",
          "examples": [
            "Family court"
          ],
          "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
        },
        "region": {
          "description": "Region details",
          "title": "Region Details",
          "type": "object",
          "properties": {
            "name": {
              "description": "region name",
              "title": "Region name",
              "type": "string",
              "default": "",
              "examples": [
                "Wales"
              ],
              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
            },
            "regionalJOH": {
              "title": "Judiciary",
              "description": "Judiciary for the region",
              "type": "array",
              "default": [],
              "items": {
                "type": "object",
                "properties": {
                  "johKnownAs": {
                    "description": "Name and salutations, titles to be presented on publications",
                    "title": "JOH Known As",
                    "type": "string",
                    "examples": [
                      "judge"
                    ],
                    "default": "",
                    "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                  }
                }
              }
            }
          }
        }
      }
    },
    "courtLists": {
      "title": "Court Lists",
      "type": "array",
      "items": {
        "title": "Court list",
        "type": "object",
        "required": ["courtHouse"],
        "properties": {
          "courtHouse": {
            "title": "Court House",
            "description": "The court house that owns the court rooms",
            "type": "object",
            "required": ["courtHouseName", "courtRoom"],
            "properties": {
              "courtHouseName": {
                "description": "Name of the court house",
                "title": "Court House Name",
                "type": "string",
                "default": "",
                "examples": [
                  "PRESTON"
                ],
                "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
              },
              "courtHouseContact": {
                "description": "The contact for the court house",
                "required": ["venueEmail", "venueTelephone"],
                "title": "Court House Contact",
                "$ref": "#/$defs/venueContact"
              },
              "courtHouseAddress": {
                "description": "The address for the court house",
                "title": "Court House Address",
                "$ref": "#/$defs/address"
              },
              "courtRoom": {
                "type": "array",
                "items": {
                  "title": "Court Room",
                  "description": "The court room that owns the court rooms",
                  "type": "object",
                  "required": ["courtRoomName", "session"],
                  "properties": {
                    "courtRoomName": {
                      "description": "Name for the court room",
                      "title": "Court Room Name",
                      "type": "string",
                      "default": "",
                      "examples": [
                        "Room 1"
                      ],
                      "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                    },
                    "session": {
                      "type": "array",
                      "items": {
                        "title": "Session",
                        "description": "Session associated with the court in the publication",
                        "required": ["sittings"],
                        "type": "object",
                        "properties": {
                          "judiciary": {
                            "title": "Judiciary",
                            "description": "Judiciary for the session",
                            "type": "array",
                            "default": [],
                            "items": {
                              "type": "object",
                              "properties": {
                                "johKnownAs": {
                                  "description": "Name and salutations, titles to be presented on publications",
                                  "title": "JOH Known As",
                                  "type": "string",
                                  "examples": [
                                    "judge"
                                  ],
                                  "default": "",
                                  "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                },
                                "isPresiding": {
                                  "description": "A flag to indicate whether a judiciary is presiding",
                                  "title": "Is Presiding",
                                  "type": "boolean",
                                  "examples": [
                                    true
                                  ],
                                  "default": "",
                                  "pattern": "^(?!.*<[^>]+>).*$"
                                }
                              }
                            }
                          },
                          "sittings": {
                            "title": "Sittings",
                            "type": "array",
                            "default": [],
                            "items":{
                              "type": "object",
                              "required": ["sittingStart", "sittingEnd", "hearing"],
                              "properties": {
                                "sittingStart": {
                                  "description": "Sitting Start Time",
                                  "title": "Sitting Start",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
                                },
                                "sittingEnd": {
                                  "description": "Sitting End Time",
                                  "title": "Sitting End",
                                  "type": "string",
                                  "default": "",
                                  "examples": [],
                                  "pattern": "^\\d{4}-\\d{2}-\\d{2}T\\d{2}:\\d{2}:\\d{2}([.]\\d{1,9})?Z$"
                                },
                                "hearing": {
                                  "type": "array",
                                  "items": {
                                    "type": "object",
                                    "description": "Hearing details of the case and associated details for the sitting",
                                    "title": "Hearing",
                                    "required": ["case"],
                                    "properties": {
                                      "hearingType": {
                                        "description": "Type of hearing being presented",
                                        "title": "Hearing Type",
                                        "type": "string",
                                        "examples": [
                                          "mda"
                                        ],
                                        "default": "",
                                        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                      },
                                      "case": {
                                        "type": "array",
                                        "items": {
                                          "type": "object",
                                          "title": "Case",
                                          "required": ["caseNumber"],
                                          "description": "Case Details",
                                          "properties": {
                                            "caseNumber": {
                                              "title": "Case Number",
                                              "description": "A number identifying a case",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "45684548"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseSequenceIndicator": {
                                              "title": "Case Sequence Indicator",
                                              "description": "The case sequence indicator",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "2 of 3"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseName": {
                                              "title": "Case Name",
                                              "description": "COP will be using both this for their lists",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "normal"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "caseType": {
                                              "title": "Case Type",
                                              "description": "This will be type of the case.",
                                              "type": "string",
                                              "default": "",
                                              "examples": [
                                                "normal"
                                              ],
                                              "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                            },
                                            "reportingRestrictionDetail": {
                                              "title": "Reporting Restrictions Detail",
                                              "description": "The detail / wording of any reporting restrictions attached to the case",
                                              "type": "array",
                                              "items": {
                                                "type": "string",
                                                "default": "",
                                                "examples": [
                                                  "This is a reporting restrictions detail"
                                                ],
                                                "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                              }
                                            }
                                          }
                                        }
                                      }
                                    }
                                  }
                                },
                                "channel": {
                                  "type": "array",
                                  "items": {
                                    "description": "Channel if different from in court",
                                    "title": "Sitting Channel",
                                    "type": "string",
                                    "examples": [
                                      "VIDEO HEARING"
                                    ],
                                    "default": "",
                                    "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
                                  }
                                }
                              }
                            }
                          }
                        }
                      }
                    }
                  }
                }
              }
            }
          }
        }
      }
    }
  }
}

=== hmcts/pip-data-management/src/test/resources/mocks/crown_firm_list/crownFirmList.json
{
  "document": {
    "publicationDate": "2023-03-03T14:07:33.871502Z",
    "documentName": "This is a document name",
    "version": "This is a document version"
  },
  "venue": {
    "venueName": "This is the venue name",
    "venueAddress": {
      "line": [
        "Address Line 1"
      ],
      "town": "Venue Town",
      "county": "Venue County",
      "postCode": "AA1 AA1"
    },
    "venueContact": {
      "venueTelephone": "01234 123 123",
      "venueEmail": "a@b.com"
    }
  },
  "locationDetails": {
    "jurisdiction": "Family"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "This is the site name",
        "courtHouseContact": {
          "venueTelephone": "01234 123 123",
          "venueEmail": "a@b.com"
        },
        "courtHouseAddress": {
          "line": [
            "Address Line 1"
          ],
          "postCode": "AA1 AA1"
        },
        "courtRoom": [
          {
            "courtRoomName": "This is the court room name",
            "session": [
              {
                "sittings": [
                  {
                    "sittingStart": "2023-03-03T14:09:30.871502Z",
                    "sittingEnd": "2023-03-03T14:10:30.871502Z",
                    "hearing": [
                      {
                        "hearingType": "Directions",
                        "case": [
                          {
                            "reportingRestrictionDetail": [
                              "Reporting Restriction detail line 1",
                              "Reporting restriction detail line 2"
                            ],
                            "caseNumber": "12341234",
                            "caseLinked": [
                              {
                                "caseId": "1234",
                                "name": "A Vs B"
                              }
                            ],
                            "caseSequenceIndicator": "2 of 3"
                          }
                        ],
                        "party": [
                          {
                            "partyRole": "DEFENDANT",
                            "individualDetails": {
                              "individualSurname": "Surname",
                              "individualForenames": "Forenames"
                            }
                          },
                          {
                            "partyRole": "PROSECUTING_AUTHORITY",
                            "organisationDetails": {
                              "organisationName": "Org name"
                            }
                          }
                        ]
                      }
                    ],
                    "channel": [
                      "Teams",
                      "Attended"
                    ]
                  }
                ],
                "judiciary": [
                  {
                    "johTitle": "Judge",
                    "johNameSurname": "Test Name",
                    "role": "JUDGE",
                    "johKnownAs": "Judge Test Name",
                    "isPresiding": true
                  },
                  {
                    "johTitle": "Magistrate",
                    "johNameSurname": "Test Name",
                    "role": "MAGISTRATE",
                    "isPresiding": false
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}

=== hmcts/pip-data-management/src/integrationTest/resources/data/crown-daily-list/crownDailyList.json
{
  "document": {
    "publicationDate": "2024-07-20T20:00:00.001Z",
    "documentName": "This is a document name",
    "version": "This is a document version"
  },
  "venue": {
    "venueName": "This is the venue name",
    "venueAddress": {
      "line": [
        "Address Line 1"
      ],
      "town": "Venue Town",
      "county": "Venue County",
      "postCode": "AA1 AA1"
    },
    "venueContact": {
      "venueTelephone": "01234 123 123",
      "venueEmail": "a@b.com"
    }
  },
  "locationDetails": {
    "jurisdiction": "Family"
  },
  "courtLists": [
    {
      "courtHouse": {
        "courtHouseName": "This is the site name",
        "courtHouseContact": {
          "venueTelephone": "01234 123 123",
          "venueEmail": "a@b.com"
        },
        "courtHouseAddress": {
          "line": [
            "Address Line 1"
          ],
          "postCode": "AA1 AA1"
        },
        "courtRoom": [
          {
            "courtRoomName": "This is the court room name",
            "session": [
              {
                "sittings": [
                  {
                    "sittingStart": "2024-07-21T10:00:00.001Z",
                    "sittingEnd": "2024-07-21T11:30:00.001Z",
                    "hearing": [
                      {
                        "hearingType": "Directions",
                        "case": [
                          {
                            "caseNumber": "12341234",
                            "reportingRestrictionDetail": [
                              "Reporting Restriction detail line 1",
                              "Reporting restriction detail line 2"
                            ],
                            "caseLinked": [
                              {
                                "caseId": "1234",
                                "name": "A Vs B"
                              }
                            ],
                            "party": [
                              {
                                "partyRole": "PROSECUTING_AUTHORITY",
                                "organisationDetails": {
                                  "organisationName": "Pro_Auth"
                                }
                              },
                              {
                                "partyRole":"DEFENDANT",
                                "individualDetails":{
                                  "individualForenames":"Forename 1",
                                  "individualSurname":"Surname 1"
                                }
                              }
                            ]
                          }
                        ]
                      }
                    ],
                    "channel": [
                      "Teams",
                      "Attended"
                    ]
                  }
                ],
                "judiciary": [
                  {
                    "johKnownAs": "Judge TestName Presiding",
                    "isPresiding": true
                  },
                  {
                    "johKnownAs": "Judge TestName",
                    "isPresiding": false
                  }
                ]
              }
            ]
          }
        ]
      }
    }
  ]
}
