=== hmcts/pip-data-management/src/main/resources/schemas/non-strategic/sscs_daily_hearing_list.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "array",
  "items": {
    "title": "Hearing list",
    "type": "object",
    "required": [
      "venue",
      "appealReferenceNumber",
      "hearingType",
      "appellant",
      "courtroom",
      "hearingTime",
      "panel",
      "fta/respondent",
      "additionalInformation"
    ],
    "properties": {
      "venue": {
        "title": "Venue",
        "type": "string",
        "default": "",
        "examples": [
          "venue"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "appealReferenceNumber": {
        "title": "Appeal reference number",
        "type": "string",
        "default": "",
        "examples": [
          "45684548"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "hearingType": {
        "title": "Type of hearing being presented",
        "type": "string",
        "default": "",
        "examples": [
          "Hearing type 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "appellant": {
        "title": "Name of appellant",
        "type": "string",
        "default": "",
        "examples": [
          "Forename Surname"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "courtroom": {
        "title": "Court room",
        "type": "string",
        "default": "",
        "examples": [
          "Court room 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "hearingTime": {
        "title": "Hearing time",
        "type": "string",
        "default": "",
        "examples": [
          "10:30am"
        ],
        "pattern": "^\\d{1,2}([:.]\\d{2})?[ap]m\\s*$"
      },
      "panel": {
        "title": "Panel",
        "type": "string",
        "default": "",
        "examples": [
          "Panel 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "fta/respondent": {
        "title": "FTA or Respondent",
        "type": "string",
        "default": "",
        "examples": [
          "Respondent 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "additionalInformation": {
        "title": "Additional information",
        "type": "string",
        "default": "",
        "examples": [
          "This is additional information"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      }
    }
  }
}

=== hmcts/pip-data-management/src/integrationTest/resources/data/non-strategic/sscs-daily-hearing-list/sscsDailyHearingList.json
[
  {
    "venue" : "Venue 1",
    "appealReferenceNumber" : "1234567",
    "hearingType" : "Directions",
    "appellant" : "Appellant 1",
    "courtroom" : "Courtroom 1",
    "hearingTime" : "10am",
    "panel" : "Panel 1",
    "fta/respondent" : "Respondent 1",
    "additionalInformation" : "Additional information 1"
  },
  {
    "venue" : "Venue 2",
    "appealReferenceNumber" : "12345672",
    "hearingType" : "Directions",
    "appellant" : "Appellant 2",
    "courtroom" : "Courtroom 2",
    "hearingTime" : "10am  ",
    "panel" : "Panel 2",
    "fta/respondent" : "Respondent 2",
    "additionalInformation" : "Additional information 2"
  }
]
