=== hmcts/pip-data-management/src/main/resources/schemas/non-strategic/ut_lands_chamber_daily_hearing_list.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "title": "Root",
  "type": "array",
  "items": {
    "title": "Hearing list",
    "type": "object",
    "required": [
      "time",
      "caseReferenceNumber",
      "caseName",
      "judges",
      "members",
      "hearingType",
      "venue",
      "modeOfHearing",
      "additionalInformation"
    ],
    "properties": {
      "time": {
        "title": "Time",
        "type": "string",
        "default": "",
        "examples": [
          "10am"
        ],
        "pattern": "^\\d{1,2}(:\\d{2})?[ap]m$"
      },
      "caseReferenceNumber": {
        "title": "Case reference number",
        "type": "string",
        "default": "",
        "examples": [
          "12345"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "caseName": {
        "title": "Case name",
        "type": "string",
        "default": "",
        "examples": [
          "Case name 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "judges": {
        "title": "Judges",
        "type": "string",
        "default": "",
        "examples": [
          "Judge 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "members": {
        "title": "Members",
        "type": "string",
        "default": "",
        "examples": [
          "Member 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "hearingType": {
        "title": "Hearing type",
        "type": "string",
        "default": "",
        "examples": [
          "Hearing type 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "venue": {
        "title": "Venue",
        "type": "string",
        "default": "",
        "examples": [
          "Venue 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "modeOfHearing": {
        "title": "Mode of hearing",
        "type": "string",
        "default": "",
        "examples": [
          "Mode of hearing 1"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      },
      "additionalInformation": {
        "title": "Additional information",
        "type": "string",
        "default": "",
        "examples": [
          "This is additional information"
        ],
        "pattern": "^(?!(.|\\r|\\n)*<[^>]+>)(.|\\r|\\n)*$"
      }
    }
  }
}

=== hmcts/pip-data-management/src/integrationTest/resources/data/non-strategic/ut-lands-chamber-daily-hearing-list/utLandsChamberDailyHearingList.json
[
  {
    "time":"10am",
    "caseReferenceNumber":"12341234",
    "caseName":"This is a case name",
    "judges":"Judge A",
    "members":"Member A",
    "hearingType":"Hearing type 1",
    "venue":"Venue 1",
    "modeOfHearing":"Mode of hearing 1",
    "additionalInformation":"Additional information 1"
  },
  {
    "time":"11am  ",
    "caseReferenceNumber":"123412342",
    "caseName":"This is a case name B",
    "judges":"Judge B",
    "members":"Member B",
    "hearingType":"Hearing type 2",
    "venue":"Venue 2",
    "modeOfHearing":"Mode of hearing 2",
    "additionalInformation":"Additional information 2"
  }
]
